language: generic
script: make
env:
  global:
  - COMMIT_AUTHOR_NAME="Travis CI"
  - COMMIT_AUTHOR_EMAIL="travis-ci@w3.org"
  - SPECS="index"
after_success:
- git commit -a -m "Committed by Travis-CI build number: $TRAVIS_JOB_ID"
- git push origin master
before_install:
- openssl aes-256-cbc -K $encrypted_ad8d97fae5ea_key -iv $encrypted_ad8d97fae5ea_iv
  -in deploy_key.enc -out deploy_key -d
